# Invoer

pm25 = float(input())
pm10 = float(input())

klassen = ["goed", "redelijk", "matig", "slecht", "zeer slecht", "extreem slecht"]


# Verwerking

if pm25 <= ...:
    niveau_pm25 = ...
elif pm25 <= ...:
    niveau_pm25 = ...
elif pm25 <= ...:
    niveau_pm25 = ...
elif pm25 <= ...:
    niveau_pm25 = ...
elif pm25 <= ...:
    niveau_pm25 = ...
else:
    niveau_pm25 = ...

if pm10 <= ...:
    niveau_pm10 = ...
elif pm10 <= ...:
    niveau_pm10 = ...
elif pm10 <= ...:
    niveau_pm10 = ...
elif pm10 <= ...:
    niveau_pm10 = ...
elif pm10 <= ...:
    niveau_pm10 = ...
else:
    niveau_pm10 = ...

niveau = ...
klasse = ...


# Uitvoer

print("EAQI-klasse:", klasse)
